title: Akash Koneti
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  A recent master's graduate in Data Science from Rochester Institute of Technology (GPA 3.70/4.00).
  I have extensive hands-on experience in data analysis, machine leaarning and NLP.
  
  <br><br>
  Having a strong passion for data science, I am eager to kickstart my career in the field. I am currently working as a Freelancer.
  <br><br>
  <a href="https://www.linkedin.com/in/akashkoneti/" target="_blank"><img src="https://img.shields.io/badge/LinkedIn-eeeeee?style=social&logo=linkedin"/></a> 
  <br>
  <a href="mailto:akashkoneti@outlook.com" target="_blank"><img src="https://img.shields.io/badge/akashkoneti%40outlook.com-eeeeee?style=social&logo=mail.ru"/></a> 
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
